# 듀얼 모멘텀 ( 절대 + 상대)

In [1]:
def data_preprocessing(read_df, base_date):   
    read_df = read_df[read_df['Date'] >= base_date].copy()
    read_df.reset_index(inplace=True, drop = True)
    read_df['STD_YM'] = read_df['Date'].map(lambda x : datetime.datetime.strptime(x, '%Y-%m-%d').strftime('%Y-%m'))
    read_df['1M_RET'] = 0.0
    ym_keys = list(read_df['STD_YM'].unique())
    return read_df, ym_keys

def create_trade_book(sample, sample_codes):
    book = pd.DataFrame()
    book = sample[sample_codes].copy()
    book['STD_YM'] = book.index.map(lambda x : datetime.datetime.strptime(x,'%Y-%m-%d').strftime('%Y-%m'))
    for c in sample_codes:
        book['p '+c] = ''
        book['r '+c] = ''
    return book

# 상대모멘텀 Positioning
def positions(book, s_codes):
    std_ym = ''
    buy_phase = False
    for s in s_codes : 
        print(s)
        for i in book.index:
            if book.loc[i,'p '+s] == '' and book.shift(1).loc[i,'p '+s] == 'ready ' + s:
                std_ym = book.loc[i,'STD_YM']
                buy_phase = True
            
            if book.loc[i,'p '+s] == '' and book.loc[i,'STD_YM'] == std_ym and buy_phase == True : 
                book.loc[i,'p '+s] = 'buy ' + s
            
            if book.loc[i,'p '+ s] == '' :
                std_ym = None
                buy_phase = False
    return book

def multi_returns(book, s_codes):
    # 손익 계산
    rtn = 1.0
    buy_dict = {}
    num = len(s_codes)
    sell_dict = {}
    
    for i in book.index:
        for s in s_codes:
            if book.loc[i, 'p ' + s] == 'buy '+ s and \
            book.shift(1).loc[i, 'p '+s] == 'ready '+s and \
            book.shift(2).loc[i, 'p '+s] == '' :     # long 진입
                buy_dict[s] = book.loc[i, s]
            elif book.loc[i, 'p '+ s] == '' and book.shift(1).loc[i, 'p '+s] == 'buy '+ s:     # long 청산
                sell_dict[s] = book.loc[i, s]
                # 손익 계산
                rtn = (sell_dict[s] / buy_dict[s]) -1
                book.loc[i, 'r '+s] = rtn
                print('개별 청산일 : ',i,' 종목코드 : ', s , 'long 진입가격 : ', buy_dict[s], ' |  long 청산가격 : ', sell_dict[s], ' | return:', round(rtn * 100, 2),'%') # 수익률 계산.

            if book.loc[i, 'p '+ s] == '':     # zero position || long 청산.
                buy_dict[s] = 0.0
                sell_dict[s] = 0.0


    acc_rtn = 1.0        
    for i in book.index:
        rtn  = 0.0
        count = 0
        for s in s_codes:
            if book.loc[i, 'p '+ s] == '' and book.shift(1).loc[i,'p '+ s] == 'buy '+ s:  # 청산. 이떄 수익률이 나오니깐.
                count += 1
                rtn += book.loc[i, 'r '+s]
        if (rtn != 0.0) & (count != 0) :
            # 내가 후보로 삼은 universe에서  1/n 이라고 가정.
            acc_rtn *= (rtn /count )  + 1
            print('누적 청산일 : ',i,'청산 종목수 : ',count, \
                  '청산 수익률 : ',round((rtn /count),4),'누적 수익률 : ' ,round(acc_rtn, 4)) # 수익률 계산.
        book.loc[i,'acc_rtn'] = acc_rtn
    
    print ('누적 수익률 :', round(acc_rtn, 4))

# 1단계 종목별 모멘텀 처리.

In [2]:
import pandas as pd
import numpy as np
import datetime

read_df = pd.read_csv('./new_us_etf_stock.csv')

In [3]:
read_df.head()

,Date,Code,Open,High,Low,Close,Adj Close,Volume
0,1980-12-12,AAPL,0.513393,0.515625,0.513393,0.513393,0.410525,117258400.0
1,1980-12-15,AAPL,0.488839,0.488839,0.486607,0.486607,0.389106,43971200.0
2,1980-12-16,AAPL,0.453125,0.453125,0.450893,0.450893,0.360548,26432000.0
3,1980-12-17,AAPL,0.462054,0.464286,0.462054,0.462054,0.369472,21610400.0
4,1980-12-18,AAPL,0.475446,0.477679,0.475446,0.475446,0.380182,18362400.0

In [4]:
month_last_df = pd.DataFrame(columns=['Date','Code','Adj Close'])
month_last_ret_df = pd.DataFrame(columns=['Date','Code','1M_RET'])
price_df, ym_keys = data_preprocessing(read_df, base_date='2010-01-02')

In [5]:
s_codes = list(price_df['Code'].unique())

for s in s_codes:
    print(s)
    for ym in ym_keys:
        try : 
            # 절대 모멘텀 사용 종가
            month_last_df= month_last_df.append(price_df.loc[price_df[(price_df['STD_YM'] == ym) \
                                                                      & (price_df['Code'] == s)].index[-1]\
                                                             ,['Date','Code','Adj Close']\
                                                            ]
                                               )
            
            # 상대 모멘텀 사용 수익률
            m_ret = price_df.loc[price_df[(price_df['STD_YM'] == ym) & (price_df['Code'] == s)].index[-1] , 'Adj Close'] \
            / price_df.loc[price_df[(price_df['STD_YM'] == ym) & (price_df['Code'] == s)].index[0] , 'Adj Close']
            price_df.loc[(price_df['STD_YM'] == ym) & (price_df['Code'] == s), ['1M_RET']] = m_ret
            
            
            month_last_ret_df= month_last_ret_df.append(price_df.loc[price_df[(price_df['STD_YM'] == ym) \
                                                                      & (price_df['Code'] == s)].index[-1]\
                                                             ,['Date','Code','1M_RET']\
                                                            ]
                                               )
        except IndexError:
            pass

AAPL
AMZN
BND
GLD
SLV
GDX
GM
MSFT
SPY
USM
USO
WMT

# 2단계. 절대*상대모멘텀 filtering 하기. Signal list

In [7]:
month_last_df

             Date  Code   Adj Close
18     2010-01-29  AAPL   24.035734
37     2010-02-26  AAPL   25.607582
60     2010-03-31  AAPL   29.409555
81     2010-04-30  AAPL   32.674633
101    2010-05-28  AAPL   32.147762
...           ...   ...         ...
28305  2019-02-28   WMT   97.939934
28326  2019-03-29   WMT   97.014641
28347  2019-04-30   WMT  102.296577
28369  2019-05-31   WMT  101.440002
28385  2019-06-24   WMT  111.276901

[1358 rows x 3 columns]

In [10]:
# 12개월  절대 모멘텀 
bf_month = 12
month_last_df.reset_index(inplace=True,drop=True)
month_last_tmp_df = month_last_df.pivot('Date','Code','Adj Close').copy()
abs_momentum_filter =  month_last_tmp_df / month_last_tmp_df.shift(bf_month) -1
abs_momentum_filter = abs_momentum_filter.where(abs_momentum_filter > 0.0 , np.nan)
abs_momentum_filter.fillna(0,inplace=True)
abs_momentum_filter[abs_momentum_filter != 0] = 1


# 유니버스 내 상위 20% 상대 모멘텀
ratio = 0.2   # 상위 20%에 드는 종목들만.
month_last_ret_df.reset_index(inplace=True,drop=True)
month_last_ret_df = month_last_ret_df.pivot('Date','Code','1M_RET').copy()
rel_momentum_filter = month_last_ret_df.rank(axis=1, ascending=False, method="max", pct=True) # 투자종목 선택할 rank
rel_momentum_filter = rel_momentum_filter.where( rel_momentum_filter < ratio , np.nan)
rel_momentum_filter.fillna(0,inplace=True)
rel_momentum_filter[rel_momentum_filter != 0] = 1

#듀얼 모멘텀.
dual_mementum_filter = abs_momentum_filter * rel_momentum_filter # 절대 모멘텀 * 상대 모멘텀 => 듀얼 모멘텀

# 3단계. signal positioning,( positioning / trading)

In [11]:
# 사실상 trading 부분.
sig_dict = dict()
for date in dual_mementum_filter.index:
    ticker_list = list(dual_mementum_filter.loc[date,dual_mementum_filter.loc[date,:] >= 1.0].index)
    sig_dict[date] = ticker_list
    
stock_c_matrix = price_df.pivot('Date','Code','Adj Close').copy()
book = create_trade_book(stock_c_matrix, s_codes)
book['STD_YM'] = book.index.map(lambda x : datetime.datetime.strptime(x,'%Y-%m-%d').strftime('%Y-%m'))

#ready 표시
for date,values in sig_dict.items():
    for stock in values:
        book.loc[date,'p '+ stock] = 'ready ' + stock
        

# # trading 부분을 만들려고 하는데
book = positions(book, s_codes)

AAPL
AMZN
BND
GLD
SLV
GDX
GM
MSFT
SPY
USM
USO
WMT

# 4단계 수익률 확인하기.

In [12]:
multi_returns(book, s_codes)

개별 청산일 :  2011-03-01  종목코드 :  AAPL long 진입가격 :  43.179466  |  long 청산가격 :  43.715107  | return: 1.24 %
개별 청산일 :  2011-03-01  종목코드 :  WMT long 진입가격 :  45.384689  |  long 청산가격 :  41.952442  | return: -7.56 %
개별 청산일 :  2011-04-01  종목코드 :  GDX long 진입가격 :  57.616322  |  long 청산가격 :  56.640263  | return: -1.69 %
개별 청산일 :  2011-05-02  종목코드 :  USM long 진입가격 :  44.592262  |  long 청산가격 :  41.984829  | return: -5.85 %
개별 청산일 :  2011-06-01  종목코드 :  GLD long 진입가격 :  150.41000400000001  |  long 청산가격 :  149.91000400000001  | return: -0.33 %
개별 청산일 :  2011-06-01  종목코드 :  SLV long 진입가격 :  33.869999  |  long 청산가격 :  35.75  | return: 5.55 %
개별 청산일 :  2011-07-01  종목코드 :  BND long 진입가격 :  66.480408  |  long 청산가격 :  65.94207800000001  | return: -0.81 %
개별 청산일 :  2011-07-01  종목코드 :  WMT long 진입가격 :  44.347271  |  long 청산가격 :  43.702071999999994  | return: -1.45 %
개별 청산일 :  2011-08-01  종목코드 :  AMZN long 진입가격 :  209.490005  |  long 청산가격 :  221.32000699999998  | return: 5.65 %
개별 청산일 :  2011-08-01  종목코드 :  MSFT long 진입가격 :  21.311052  |  long 청산가격 :  22.334837  | return: 4.8 %
개별 청산일 :  2011-09-01  종목코드 :  AAPL long 진입가격 :  49.652069  |  long 청산가격 :  47.684769  | return: -3.96 %
개별 청산일 :  2011-09-01  종목코드 :  SLV long 진입가격 :  38.290001000000004  |  long 청산가격 :  40.52  | return: 5.82 %
개별 청산일 :  2011-10-03  종목코드 :  GLD long 진입가격 :  177.869995  |  long 청산가격 :  160.96000700000002  | return: -9.51 %
개별 청산일 :  2011-10-03  종목코드 :  GDX long 진입가격 :  60.06123  |  long 청산가격 :  51.598824  | return: -14.09 %
개별 청산일 :  2011-11-01  종목코드 :  AMZN long 진입가격 :  211.979996  |  long 청산가격 :  212.100006  | return: 0.06 %
개별 청산일 :  2011-11-01  종목코드 :  BND long 진입가격 :  68.937309  |  long 청산가격 :  69.13556700000001  | return: 0.29 %
개별 청산일 :  2012-01-03  종목코드 :  USO long 진입가격 :  35.200001  |  long 청산가격 :  39.689999  | return: 12.76 %
개별 청산일 :  2012-02-01  종목코드 :  AAPL long 진입가격 :  51.464207  |  long 청산가격 :  57.090816000000004  | return: 10.93 %
개별 청산일 :  2012-03-01  종목코드 :  SLV long 진입가격 :  32.77  |  long 청산가격 :  34.439999  | return: 5.1 %
개별 청산일 :  2012-04-02  종목코드 :  USO long 진입가격 :  41.75  |  long 청산가격 :  40.029999  | return: -4.12 %
개별 청산일 :  2012-05-01  종목코드 :  AAPL long 진입가격 :  68.138809  |  long 청산가격 :  72.85183  | return: 6.92 %
개별 청산일 :  2012-06-01  종목코드 :  AMZN long 진입가격 :  198.050003  |  long 청산가격 :  208.220001  | return: 5.14 %
개별 청산일 :  2012-07-02  종목코드 :  BND long 진입가격 :  70.17403399999999  |  long 청산가격 :  71.12571700000001  | return: 1.36 %
개별 청산일 :  2012-07-02  종목코드 :  WMT long 진입가격 :  54.992363  |  long 청산가격 :  58.180325  | return: 5.8 %
개별 청산일 :  2012-08-01  종목코드 :  AMZN long 진입가격 :  229.32000699999998  |  long 청산가격 :  232.08999599999999  | return: 1.21 %
개별 청산일 :  2012-08-01  종목코드 :  MSFT long 진입가격 :  25.711756  |  long 청산가격 :  24.744194  | return: -3.76 %
개별 청산일 :  2012-09-04  종목코드 :  WMT long 진입가격 :  61.762618999999994  |  long 청산가격 :  62.003403000000006  | return: 0.39 %
개별 청산일 :  2012-11-01  종목코드 :  SLV long 진입가격 :  33.650002  |  long 청산가격 :  31.219998999999998  | return: -7.22 %
개별 청산일 :  2012-12-03  종목코드 :  WMT long 진입가격 :  61.952801  |  long 청산가격 :  60.173092000000004  | return: -2.87 %
개별 청산일 :  2013-01-02  종목코드 :  AMZN long 진입가격 :  250.330002  |  long 청산가격 :  257.309998  | return: 2.79 %
개별 청산일 :  2013-01-02  종목코드 :  SLV long 진입가격 :  32.52  |  long 청산가격 :  29.92  | return: -8.0 %
개별 청산일 :  2013-02-01  종목코드 :  GM long 진입가격 :  23.027262  |  long 청산가격 :  22.268387  | return: -3.3 %
개별 청산일 :  2013-04-01  종목코드 :  BND long 진입가격 :  71.360786  |  long 청산가격 :  71.298386  | return: -0.09 %
개별 청산일 :  2013-05-01  종목코드 :  WMT long 진입가격 :  60.845825  |  long 청산가격 :  66.63323199999999  | return: 9.51 %
개별 청산일 :  2013-06-03  종목코드 :  MSFT long 진입가격 :  28.170472999999998  |  long 청산가격 :  30.856287  | return: 9.53 %
개별 청산일 :  2013-07-01  종목코드 :  GM long 진입가격 :  23.857288  |  long 청산가격 :  26.877001  | return: 12.66 %
개별 청산일 :  2013-08-01  종목코드 :  AMZN long 진입가격 :  266.880005  |  long 청산가격 :  305.570007  | return: 14.5 %
개별 청산일 :  2013-09-03  종목코드 :  USM long 진입가격 :  34.709998999999996  |  long 청산가격 :  42.900002  | return: 23.6 %
개별 청산일 :  2013-11-01  종목코드 :  USM long 진입가격 :  45.830002  |  long 청산가격 :  47.029999  | return: 2.62 %
개별 청산일 :  2014-01-02  종목코드 :  AMZN long 진입가격 :  320.950012  |  long 청산가격 :  397.97000099999997  | return: 24.0 %
개별 청산일 :  2014-01-02  종목코드 :  MSFT long 진입가격 :  33.825386  |  long 청산가격 :  32.690540000000006  | return: -3.36 %
개별 청산일 :  2014-02-03  종목코드 :  GM long 진입가격 :  32.370987  |  long 청산가격 :  27.865121999999996  | return: -13.92 %
개별 청산일 :  2014-02-03  종목코드 :  USO long 진입가격 :  34.23  |  long 청산가격 :  34.52  | return: 0.85 %
개별 청산일 :  2014-03-03  종목코드 :  USM long 진입가격 :  43.099998  |  long 청산가격 :  39.5  | return: -8.35 %
개별 청산일 :  2014-05-01  종목코드 :  MSFT long 진입가격 :  36.711403000000004  |  long 청산가격 :  35.452824  | return: -3.43 %
개별 청산일 :  2014-05-01  종목코드 :  USM long 진입가격 :  41.220001  |  long 청산가격 :  41.98  | return: 1.84 %
개별 청산일 :  2014-06-02  종목코드 :  WMT long 진입가격 :  69.704483  |  long 청산가격 :  67.548828  | return: -3.09 %
개별 청산일 :  2014-07-01  종목코드 :  AAPL long 진입가격 :  77.01355  |  long 청산가격 :  85.713371  | return: 11.3 %
개별 청산일 :  2014-07-01  종목코드 :  USO long 진입가격 :  37.529999  |  long 청산가격 :  38.860001000000004  | return: 3.54 %
개별 청산일 :  2014-08-01  종목코드 :  SLV long 진입가격 :  20.209999  |  long 청산가격 :  19.52  | return: -3.41 %
개별 청산일 :  2014-08-01  종목코드 :  GDX long 진입가격 :  25.431620000000002  |  long 청산가격 :  25.392851  | return: -0.15 %
개별 청산일 :  2014-09-02  종목코드 :  MSFT long 진입가격 :  38.255699  |  long 청산가격 :  40.497501  | return: 5.86 %
개별 청산일 :  2014-10-01  종목코드 :  AAPL long 진입가격 :  88.105499  |  long 청산가격 :  91.35305799999999  | return: 3.69 %
개별 청산일 :  2014-10-01  종목코드 :  AMZN long 진입가격 :  342.380005  |  long 청산가격 :  317.459991  | return: -7.28 %
개별 청산일 :  2014-11-03  종목코드 :  MSFT long 진입가격 :  41.225014  |  long 청산가격 :  42.608146999999995  | return: 3.36 %
개별 청산일 :  2014-11-03  종목코드 :  WMT long 진입가격 :  67.42693299999999  |  long 청산가격 :  67.56864200000001  | return: 0.21 %
개별 청산일 :  2014-12-01  종목코드 :  AAPL long 진입가격 :  100.766525  |  long 청산가격 :  106.448647  | return: 5.64 %
개별 청산일 :  2015-01-02  종목코드 :  WMT long 진입가격 :  76.37350500000001  |  long 청산가격 :  76.515121  | return: 0.19 %
개별 청산일 :  2015-04-01  종목코드 :  AAPL long 진입가격 :  119.88951899999999  |  long 청산가격 :  115.394478  | return: -3.75 %
개별 청산일 :  2015-04-01  종목코드 :  GM long 진입가격 :  30.781675  |  long 청산가격 :  30.316509000000003  | return: -1.51 %
개별 청산일 :  2015-05-01  종목코드 :  BND long 진입가격 :  74.701561  |  long 청산가격 :  73.93969  | return: -1.02 %
개별 청산일 :  2015-06-01  종목코드 :  MSFT long 진입가격 :  44.292522  |  long 청산가격 :  43.270255999999996  | return: -2.31 %
개별 청산일 :  2015-08-03  종목코드 :  BND long 진입가격 :  72.798828  |  long 청산가격 :  73.787933  | return: 1.36 %
개별 청산일 :  2015-09-01  종목코드 :  AMZN long 진입가격 :  437.39001500000006  |  long 청산가격 :  496.540009  | return: 13.52 %
개별 청산일 :  2015-09-01  종목코드 :  MSFT long 진입가격 :  42.885490000000004  |  long 청산가격 :  38.566497999999996  | return: -10.07 %
개별 청산일 :  2016-01-04  종목코드 :  AMZN long 진입가격 :  628.349976  |  long 청산가격 :  636.98999  | return: 1.38 %
개별 청산일 :  2016-02-01  종목코드 :  MSFT long 진입가격 :  49.098042  |  long 청산가격 :  50.793755  | return: 3.45 %
개별 청산일 :  2016-05-02  종목코드 :  USM long 진입가격 :  41.529999  |  long 청산가격 :  43.669998  | return: 5.15 %
개별 청산일 :  2016-06-01  종목코드 :  GDX long 진입가격 :  24.982004  |  long 청산가격 :  22.354908  | return: -10.52 %
개별 청산일 :  2016-08-01  종목코드 :  SLV long 진입가격 :  18.74  |  long 청산가격 :  19.43  | return: 3.68 %
개별 청산일 :  2016-08-01  종목코드 :  GDX long 진입가격 :  28.583189  |  long 청산가격 :  30.432980999999998  | return: 6.47 %
개별 청산일 :  2016-09-01  종목코드 :  GM long 진입가격 :  27.373268  |  long 청산가격 :  27.810545  | return: 1.6 %
개별 청산일 :  2016-10-03  종목코드 :  MSFT long 진입가격 :  53.277106999999994  |  long 청산가격 :  54.40506  | return: 2.12 %
개별 청산일 :  2016-11-01  종목코드 :  AMZN long 진입가격 :  836.73999  |  long 청산가격 :  785.409973  | return: -6.13 %
개별 청산일 :  2016-12-01  종목코드 :  MSFT long 진입가격 :  56.660099  |  long 청산가격 :  56.470524  | return: -0.33 %
개별 청산일 :  2017-01-03  종목코드 :  GM long 진입가격 :  32.241119  |  long 청산가격 :  31.445760999999997  | return: -2.47 %
개별 청산일 :  2017-02-01  종목코드 :  AAPL long 진입가격 :  111.70983100000001  |  long 청산가격 :  123.828148  | return: 10.85 %
개별 청산일 :  2017-02-01  종목코드 :  USM long 진입가격 :  45.669998  |  long 청산가격 :  42.669998  | return: -6.57 %
개별 청산일 :  2017-03-01  종목코드 :  AMZN long 진입가격 :  832.349976  |  long 청산가격 :  853.080017  | return: 2.49 %
개별 청산일 :  2017-03-01  종목코드 :  GDX long 진입가격 :  23.534592  |  long 청산가격 :  22.676095999999998  | return: -3.65 %
개별 청산일 :  2017-04-03  종목코드 :  AAPL long 진입가격 :  135.028976  |  long 청산가격 :  138.805832  | return: 2.8 %
개별 청산일 :  2017-05-01  종목코드 :  AMZN long 진입가격 :  891.51001  |  long 청산가격 :  948.2299800000001  | return: 6.36 %
개별 청산일 :  2017-07-03  종목코드 :  AMZN long 진입가격 :  995.9500119999999  |  long 청산가격 :  953.659973  | return: -4.25 %
개별 청산일 :  2017-07-03  종목코드 :  WMT long 진입가격 :  66.37087199999999  |  long 청산가격 :  71.997231  | return: 8.48 %
개별 청산일 :  2017-08-01  종목코드 :  GM long 진입가격 :  32.505835999999995  |  long 청산가격 :  31.765617  | return: -2.28 %
개별 청산일 :  2017-09-01  종목코드 :  MSFT long 진입가격 :  70.052635  |  long 청산가격 :  71.745491  | return: 2.42 %
개별 청산일 :  2017-09-01  종목코드 :  USO long 진입가격 :  10.09  |  long 청산가격 :  9.67  | return: -4.16 %
개별 청산일 :  2017-10-02  종목코드 :  AAPL long 진입가격 :  159.74168400000002  |  long 청산가격 :  149.770599  | return: -6.24 %
개별 청산일 :  2017-11-01  종목코드 :  GM long 진입가격 :  39.312798  |  long 청산가격 :  40.226833  | return: 2.33 %
개별 청산일 :  2017-12-01  종목코드 :  MSFT long 진입가격 :  80.71125  |  long 청산가격 :  82.169785  | return: 1.81 %
개별 청산일 :  2018-01-02  종목코드 :  AMZN long 진입가격 :  1103.680054  |  long 청산가격 :  1189.01001  | return: 7.73 %
개별 청산일 :  2018-01-02  종목코드 :  WMT long 진입가격 :  93.59097299999999  |  long 청산가격 :  95.282616  | return: 1.81 %
개별 청산일 :  2018-02-01  종목코드 :  SLV long 진입가격 :  16.209999  |  long 청산가격 :  16.25  | return: 0.25 %
개별 청산일 :  2018-02-01  종목코드 :  GDX long 진입가격 :  23.694632000000002  |  long 청산가격 :  23.575264  | return: -0.5 %
개별 청산일 :  2018-03-01  종목코드 :  MSFT long 진입가격 :  91.921715  |  long 청산가격 :  90.972031  | return: -1.03 %
개별 청산일 :  2018-04-02  종목코드 :  AAPL long 진입가격 :  171.713928  |  long 청산가격 :  163.550171  | return: -4.75 %
개별 청산일 :  2018-04-02  종목코드 :  AMZN long 진입가격 :  1390.0  |  long 청산가격 :  1371.98999  | return: -1.3 %
개별 청산일 :  2018-06-01  종목코드 :  AMZN long 진입가격 :  1582.26001  |  long 청산가격 :  1641.540039  | return: 3.75 %
개별 청산일 :  2018-06-01  종목코드 :  USO long 진입가격 :  12.74  |  long 청산가격 :  13.25  | return: 4.0 %
개별 청산일 :  2018-07-02  종목코드 :  AAPL long 진입가격 :  187.387604  |  long 청산가격 :  184.373459  | return: -1.61 %
개별 청산일 :  2018-07-02  종목코드 :  GM long 진입가격 :  41.072224  |  long 청산가격 :  37.882149  | return: -7.77 %
개별 청산일 :  2018-08-01  종목코드 :  AMZN long 진입가격 :  1713.780029  |  long 청산가격 :  1797.1700440000002  | return: 4.87 %
개별 청산일 :  2018-08-01  종목코드 :  USO long 진입가격 :  14.96  |  long 청산가격 :  14.09  | return: -5.82 %
개별 청산일 :  2018-09-04  종목코드 :  MSFT long 진입가격 :  104.581749  |  long 청산가격 :  110.348  | return: 5.51 %
개별 청산일 :  2018-09-04  종목코드 :  WMT long 진입가격 :  86.328728  |  long 청산가격 :  93.83638  | return: 8.7 %
개별 청산일 :  2018-10-01  종목코드 :  AAPL long 진입가격 :  225.72489900000002  |  long 청산가격 :  224.637604  | return: -0.48 %
개별 청산일 :  2018-11-01  종목코드 :  USO long 진입가격 :  15.95  |  long 청산가격 :  13.46  | return: -15.61 %
개별 청산일 :  2019-01-02  종목코드 :  MSFT long 진입가격 :  111.201698  |  long 청산가격 :  100.31864200000001  | return: -9.79 %
개별 청산일 :  2019-01-02  종목코드 :  USM long 진입가격 :  42.490002000000004  |  long 청산가격 :  52.470001  | return: 23.49 %
개별 청산일 :  2019-04-01  종목코드 :  MSFT long 진입가격 :  112.11498999999999  |  long 청산가격 :  118.581055  | return: 5.77 %
개별 청산일 :  2019-04-01  종목코드 :  WMT long 진입가격 :  96.89119000000001  |  long 청산가격 :  97.303108  | return: 0.43 %
개별 청산일 :  2019-05-01  종목코드 :  AAPL long 진입가격 :  190.506363  |  long 청산가격 :  209.712402  | return: 10.08 %
개별 청산일 :  2019-06-03  종목코드 :  AMZN long 진입가격 :  1911.52002  |  long 청산가격 :  1692.689941  | return: -11.45 %
개별 청산일 :  2019-06-03  종목코드 :  MSFT long 진입가격 :  127.40837900000001  |  long 청산가격 :  119.839996  | return: -5.94 %
누적 청산일 :  2011-03-01 청산 종목수 :  2 청산 수익률 :  -0.0316 누적 수익률 :  0.9684
누적 청산일 :  2011-04-01 청산 종목수 :  1 청산 수익률 :  -0.0169 누적 수익률 :  0.952
누적 청산일 :  2011-05-02 청산 종목수 :  1 청산 수익률 :  -0.0585 누적 수익률 :  0.8963
누적 청산일 :  2011-06-01 청산 종목수 :  2 청산 수익률 :  0.0261 누적 수익률 :  0.9197
누적 청산일 :  2011-07-01 청산 종목수 :  2 청산 수익률 :  -0.0113 누적 수익률 :  0.9093
누적 청산일 :  2011-08-01 청산 종목수 :  2 청산 수익률 :  0.0523 누적 수익률 :  0.9568
누적 청산일 :  2011-09-01 청산 종목수 :  2 청산 수익률 :  0.0093 누적 수익률 :  0.9657
누적 청산일 :  2011-10-03 청산 종목수 :  2 청산 수익률 :  -0.118 누적 수익률 :  0.8518
누적 청산일 :  2011-11-01 청산 종목수 :  2 청산 수익률 :  0.0017 누적 수익률 :  0.8532
누적 청산일 :  2012-01-03 청산 종목수 :  1 청산 수익률 :  0.1276 누적 수익률 :  0.9621
누적 청산일 :  2012-02-01 청산 종목수 :  1 청산 수익률 :  0.1093 누적 수익률 :  1.0673
누적 청산일 :  2012-03-01 청산 종목수 :  1 청산 수익률 :  0.051 누적 수익률 :  1.1217
누적 청산일 :  2012-04-02 청산 종목수 :  1 청산 수익률 :  -0.0412 누적 수익률 :  1.0754
누적 청산일 :  2012-05-01 청산 종목수 :  1 청산 수익률 :  0.0692 누적 수익률 :  1.1498
누적 청산일 :  2012-06-01 청산 종목수 :  1 청산 수익률 :  0.0514 누적 수익률 :  1.2089
누적 청산일 :  2012-07-02 청산 종목수 :  2 청산 수익률 :  0.0358 누적 수익률 :  1.2521
누적 청산일 :  2012-08-01 청산 종목수 :  2 청산 수익률 :  -0.0128 누적 수익률 :  1.2361
누적 청산일 :  2012-09-04 청산 종목수 :  1 청산 수익률 :  0.0039 누적 수익률 :  1.2409
누적 청산일 :  2012-11-01 청산 종목수 :  1 청산 수익률 :  -0.0722 누적 수익률 :  1.1513
누적 청산일 :  2012-12-03 청산 종목수 :  1 청산 수익률 :  -0.0287 누적 수익률 :  1.1182
누적 청산일 :  2013-01-02 청산 종목수 :  2 청산 수익률 :  -0.026 누적 수익률 :  1.0891
누적 청산일 :  2013-02-01 청산 종목수 :  1 청산 수익률 :  -0.033 누적 수익률 :  1.0532
누적 청산일 :  2013-04-01 청산 종목수 :  1 청산 수익률 :  -0.0009 누적 수익률 :  1.0523
누적 청산일 :  2013-05-01 청산 종목수 :  1 청산 수익률 :  0.0951 누적 수익률 :  1.1524
누적 청산일 :  2013-06-03 청산 종목수 :  1 청산 수익률 :  0.0953 누적 수익률 :  1.2623
누적 청산일 :  2013-07-01 청산 종목수 :  1 청산 수익률 :  0.1266 누적 수익률 :  1.4221
누적 청산일 :  2013-08-01 청산 종목수 :  1 청산 수익률 :  0.145 누적 수익률 :  1.6282
누적 청산일 :  2013-09-03 청산 종목수 :  1 청산 수익률 :  0.236 누적 수익률 :  2.0124
누적 청산일 :  2013-11-01 청산 종목수 :  1 청산 수익률 :  0.0262 누적 수익률 :  2.0651
누적 청산일 :  2014-01-02 청산 종목수 :  2 청산 수익률 :  0.1032 누적 수익률 :  2.2782
누적 청산일 :  2014-02-03 청산 종목수 :  2 청산 수익률 :  -0.0654 누적 수익률 :  2.1293
누적 청산일 :  2014-03-03 청산 종목수 :  1 청산 수익률 :  -0.0835 누적 수익률 :  1.9515
누적 청산일 :  2014-05-01 청산 종목수 :  2 청산 수익률 :  -0.0079 누적 수익률 :  1.936
누적 청산일 :  2014-06-02 청산 종목수 :  1 청산 수익률 :  -0.0309 누적 수익률 :  1.8761
누적 청산일 :  2014-07-01 청산 종목수 :  2 청산 수익률 :  0.0742 누적 수익률 :  2.0154
누적 청산일 :  2014-08-01 청산 종목수 :  2 청산 수익률 :  -0.0178 누적 수익률 :  1.9794
누적 청산일 :  2014-09-02 청산 종목수 :  1 청산 수익률 :  0.0586 누적 수익률 :  2.0954
누적 청산일 :  2014-10-01 청산 종목수 :  2 청산 수익률 :  -0.018 누적 수익률 :  2.0578
누적 청산일 :  2014-11-03 청산 종목수 :  2 청산 수익률 :  0.0178 누적 수익률 :  2.0944
누적 청산일 :  2014-12-01 청산 종목수 :  1 청산 수익률 :  0.0564 누적 수익률 :  2.2126
누적 청산일 :  2015-01-02 청산 종목수 :  1 청산 수익률 :  0.0019 누적 수익률 :  2.2167
누적 청산일 :  2015-04-01 청산 종목수 :  2 청산 수익률 :  -0.0263 누적 수익률 :  2.1584
누적 청산일 :  2015-05-01 청산 종목수 :  1 청산 수익률 :  -0.0102 누적 수익률 :  2.1363
누적 청산일 :  2015-06-01 청산 종목수 :  1 청산 수익률 :  -0.0231 누적 수익률 :  2.087
누적 청산일 :  2015-08-03 청산 종목수 :  1 청산 수익률 :  0.0136 누적 수익률 :  2.1154
누적 청산일 :  2015-09-01 청산 종목수 :  2 청산 수익률 :  0.0173 누적 수익률 :  2.1519
누적 청산일 :  2016-01-04 청산 종목수 :  1 청산 수익률 :  0.0138 누적 수익률 :  2.1815
누적 청산일 :  2016-02-01 청산 종목수 :  1 청산 수익률 :  0.0345 누적 수익률 :  2.2568
누적 청산일 :  2016-05-02 청산 종목수 :  1 청산 수익률 :  0.0515 누적 수익률 :  2.3731
누적 청산일 :  2016-06-01 청산 종목수 :  1 청산 수익률 :  -0.1052 누적 수익률 :  2.1236
누적 청산일 :  2016-08-01 청산 종목수 :  2 청산 수익률 :  0.0508 누적 수익률 :  2.2314
누적 청산일 :  2016-09-01 청산 종목수 :  1 청산 수익률 :  0.016 누적 수익률 :  2.267
누적 청산일 :  2016-10-03 청산 종목수 :  1 청산 수익률 :  0.0212 누적 수익률 :  2.315
누적 청산일 :  2016-11-01 청산 종목수 :  1 청산 수익률 :  -0.0613 누적 수익률 :  2.173
누적 청산일 :  2016-12-01 청산 종목수 :  1 청산 수익률 :  -0.0033 누적 수익률 :  2.1657
누적 청산일 :  2017-01-03 청산 종목수 :  1 청산 수익률 :  -0.0247 누적 수익률 :  2.1123
누적 청산일 :  2017-02-01 청산 종목수 :  2 청산 수익률 :  0.0214 누적 수익률 :  2.1575
누적 청산일 :  2017-03-01 청산 종목수 :  2 청산 수익률 :  -0.0058 누적 수익률 :  2.145
누적 청산일 :  2017-04-03 청산 종목수 :  1 청산 수익률 :  0.028 누적 수익률 :  2.205
누적 청산일 :  2017-05-01 청산 종목수 :  1 청산 수익률 :  0.0636 누적 수익률 :  2.3453
누적 청산일 :  2017-07-03 청산 종목수 :  2 청산 수익률 :  0.0212 누적 수익률 :  2.3949
누적 청산일 :  2017-08-01 청산 종목수 :  1 청산 수익률 :  -0.0228 누적 수익률 :  2.3404
누적 청산일 :  2017-09-01 청산 종목수 :  2 청산 수익률 :  -0.0087 누적 수익률 :  2.32
누적 청산일 :  2017-10-02 청산 종목수 :  1 청산 수익률 :  -0.0624 누적 수익률 :  2.1751
누적 청산일 :  2017-11-01 청산 종목수 :  1 청산 수익률 :  0.0233 누적 수익률 :  2.2257
누적 청산일 :  2017-12-01 청산 종목수 :  1 청산 수익률 :  0.0181 누적 수익률 :  2.2659
누적 청산일 :  2018-01-02 청산 종목수 :  2 청산 수익률 :  0.0477 누적 수익률 :  2.374
누적 청산일 :  2018-02-01 청산 종목수 :  2 청산 수익률 :  -0.0013 누적 수익률 :  2.371
누적 청산일 :  2018-03-01 청산 종목수 :  1 청산 수익률 :  -0.0103 누적 수익률 :  2.3465
누적 청산일 :  2018-04-02 청산 종목수 :  2 청산 수익률 :  -0.0302 누적 수익률 :  2.2755
누적 청산일 :  2018-06-01 청산 종목수 :  2 청산 수익률 :  0.0387 누적 수익률 :  2.3637
누적 청산일 :  2018-07-02 청산 종목수 :  2 청산 수익률 :  -0.0469 누적 수익률 :  2.2529
누적 청산일 :  2018-08-01 청산 종목수 :  2 청산 수익률 :  -0.0047 누적 수익률 :  2.2422
누적 청산일 :  2018-09-04 청산 종목수 :  2 청산 수익률 :  0.0711 누적 수익률 :  2.4015
누적 청산일 :  2018-10-01 청산 종목수 :  1 청산 수익률 :  -0.0048 누적 수익률 :  2.3899
누적 청산일 :  2018-11-01 청산 종목수 :  1 청산 수익률 :  -0.1561 누적 수익률 :  2.0168
누적 청산일 :  2019-01-02 청산 종목수 :  2 청산 수익률 :  0.0685 누적 수익률 :  2.155
누적 청산일 :  2019-04-01 청산 종목수 :  2 청산 수익률 :  0.031 누적 수익률 :  2.2217
누적 청산일 :  2019-05-01 청산 종목수 :  1 청산 수익률 :  0.1008 누적 수익률 :  2.4457
누적 청산일 :  2019-06-03 청산 종목수 :  2 청산 수익률 :  -0.0869 누적 수익률 :  2.233
누적 수익률 : 2.233

In [18]:
book.loc['2011-01-30':'2011-02-01',:]  # 진입 포지션 확인

Code,AAPL,AMZN,BND,GLD,SLV,GDX,GM,MSFT,SPY,USM,...,r MSFT,p SPY,r SPY,p USM,r USM,p USO,r USO,p WMT,r WMT,acc_rtn
Date,,,,,,,,,,,,,,,,,,,,,
2011-01-31,42.464890,169.639999,64.351532,129.869995,27.389999,51.096581,28.845346,22.431110,108.451126,41.804710,...,,,,,,,,ready WMT,,1.0
2011-02-01,43.179466,172.110001,64.227013,130.800003,27.870001,52.536987,28.813723,22.641428,110.187263,42.568073,...,,,,,,,,buy WMT,,1.0

In [19]:
book.loc['2011-02-26':'2011-03-01',:]  # 청산 포지션 확인

Code,AAPL,AMZN,BND,GLD,SLV,GDX,GM,MSFT,SPY,USM,...,r MSFT,p SPY,r SPY,p USM,r USM,p USO,r USO,p WMT,r WMT,acc_rtn
Date,,,,,,,,,,,,,,,,,,,,,
2011-02-28,44.203182,173.289993,64.540276,137.660004,33.110001,56.697117,26.505461,21.627945,112.218414,42.868267,...,,,,,,,,buy WMT,,1.00000
2011-03-01,43.715107,169.440002,64.509674,140.029999,33.869999,57.616322,26.046976,21.286194,110.347397,41.521667,...,,,,,,,,,-0.0756257,0.96839